### ISSUE TITLE
Incorrect rounding on division

### ISSUE THREAD

**Issue by veddan** [wbhart/bsdnt#10]
All division functions declared in `zz.h` are documented as to round toward minus infinity. Thus 1 / -2 == -0.5 should round to -1. However, the following program prints '0' and not the expected '-1':

``` C
#include "bsdnt/zz.h"
int main(void) {
  zz_t one, minus_two, quot;
  zz_init(one); zz_init(minus_two); zz_init(quot);
  zz_set_str(one, "1");
  zz_set_str(minus_two, "-2");
  zz_div(quot, one, minus_two);
  zz_print(quot);
}
```

Using `zz_divrem` instead of `zz_div` gives the same result.

**Comment by wbhart** [comment]
Fixed in master.
