### ISSUE TITLE
question about use of `nn_copy` in `zz_get_str`

### ISSUE THREAD

**Issue by turtle-dragonfly** [wbhart/bsdnt#24]
In the [implementation of](https://github.com/wbhart/bsdnt/blob/97053f366618b0e987a76bc6d6992165c8ea843e/zz.c#L878) `zz_get_str`, it goes through the process of copying the input to a temporary (`t`) before using `nn_get_str` to do most of the work.

Is there any reason to make that copy?

As far as I can tell, it is unnecessary, since the input is read-only, and can just be used directly.

But, I am just starting to get familiar with this library, so not sure if I'm missing something...

**Comment by wbhart** [comment]
It looks like the current quadratic nn_get_str doesn't modify its input. I don't recall if I had planned to implement something subquadratic which did. But it does look at the moment as though that restriction could be lifted.

**Comment by turtle-dragonfly** [comment]
good to know; thanks!
