### ISSUE TITLE
question re: Windows/MSVC support

### ISSUE THREAD

**Issue by turtle-dragonfly** [wbhart/bsdnt#25]
I am currently in the process of porting bsdnt to run on Windows, for my local project.

Are you interested in changes like that being merged back into the mainline?

I notice that in older releases, MSVC was supported, but it was removed in [fb3037b](https://github.com/wbhart/bsdnt/commit/fb3037bb759220c80aa78eb54c4d53cc7100d246).

Is it an anti-feature for this project?

I realize that the autoconf/bash-driven configuration for the `arch/inline/xxx` code is not easy to convert. I'm not planning on dealing with that, just updating the main plain-C codebase to compile under MSVC.

**Comment by wbhart** [comment]
I'm not really actively maintaining this project at the moment. It's offered as is for anyone interested.

I'm not interested in adding visual solution files back into the project, but I might consider a CMake build that works for MSVC.

One of the issues here is that some of the code is assembly language and this is very toolchain dependent. I'm not keen on making it more difficult to maintain in the future. This project was mainly designed to be a really simple, easy to maintain project which doesn't have terrible performance. Making it all singing and all dancing wasn't a design goal.

**Comment by turtle-dragonfly** [comment]
Ok, thanks. I suppose for now I'll just keep it in my fork, in case anyone wants to reference it.

Aside: I've also hit some issues with using 32-bit `word_t` - various casts to `(long)` fail, and some other issues. I think that this is meant to be a supported configuration, so would you be interested in those changes?

**Comment by wbhart** [comment]
Sure, if they aren't too extensive.
